spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-gsf-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-gsf-test
#请保存为utf-8格式